stages:
  - sync

sync_to_github:
  stage: sync
  image: alpine/git:latest
  before_script:
    - git config --global user.email "ci@gitlab.com"
    - git config --global user.name "GitLab CI"
  script:
    # Remove any existing github remote
    - git remote remove github || true
    # Add the correct GitHub repository URL
    - git remote add github https://$GITHUB_TOKEN@github.com/ElliotBadinger/echo.git
    # Fetch all remotes to ensure we have the latest
    - git fetch --all
    # Push the current branch to GitHub
    - git push github HEAD:refactor/phase1-modularization-kts-hilt --force-with-lease
  only:
    - refactor/phase1-modularization-kts-hilt
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0