# Documentation Automation Configuration
# Version: 2.0 - Unified Documentation System
# Purpose: Configure automated documentation management and MCP integration

# Global Configuration
version: "2.0"
system: "Echo Android Project Documentation"
last_updated: "2025-09-06"

# Documentation Structure
structure:
  base_path: "docs/"
  sections:
    - agent-workflow
    - project-state
    - frameworks
    - mcp-integration
    - templates
    - automation

# Automated Change Log Generation
change_log:
  auto_generate: true
  sources:
    - git_commits
    - ci_results
    - test_results
    - mcp_usage_stats
  format:
    template: "templates/change-log-template.md"
    include_metrics: true
    include_research: true
    include_mcp_usage: true
  triggers:
    - git_commit
    - ci_completion
    - manual_request

# Living Documentation System
living_docs:
  auto_update:
    - current_status.md:
        sources: [ci_status, test_results, build_metrics, mcp_server_status]
        frequency: "on_change"
        update_fields: ["build_status", "test_results", "ci_status", "mcp_health"]
    - priorities.md:
        sources: [change_log, current_status, framework_progress]
        frequency: "daily"
        update_fields: ["next_priority", "progress_status", "blockers"]
    - research-findings.md:
        sources: [mcp_research_logs, change_log]
        frequency: "on_research_completion"
        update_fields: ["latest_findings", "research_trends"]

# MCP Integration Automation
mcp_integration:
  auto_document:
    - context7_usage:
        track_queries: true
        document_success_rate: true
        suggest_improvements: true
        metrics:
          - query_count
          - usefulness_rating
          - time_saved
          - implementation_impact
    - brave_search_usage:
        track_effectiveness: true
        document_research_findings: true
        metrics:
          - search_count
          - relevance_score
          - research_quality
          - time_efficiency
    - github_mcp_usage:
        track_ci_integration: true
        document_workflow_efficiency: true
        metrics:
          - operation_count
          - success_rate
          - time_saved
          - development_impact
    - playwright_usage:
        track_content_extraction: true
        document_source_quality: true
        metrics:
          - extraction_count
          - completeness_score
          - research_value
          - time_efficiency

  optimization_targets:
    context7:
      target_usage: 15-20
      weekly_target: 15
      success_metrics:
        - usefulness_rating: ">7.0"
        - time_saved_hours: ">2.0"
        - implementation_rate: ">80%"
    brave_search:
      target_usage: 10-15
      weekly_target: 12
      success_metrics:
        - relevance_score: ">7.0"
        - research_efficiency: ">60%"
        - finding_quality: ">8.0"
    github_mcp:
      target_usage: "maintain_high"
      weekly_target: 25
      success_metrics:
        - operation_success: ">95%"
        - ci_efficiency: ">80%"
        - development_acceleration: ">30%"
    playwright:
      target_usage: 8-12
      weekly_target: 10
      success_metrics:
        - extraction_quality: ">8.0"
        - completeness_rate: ">90%"
        - research_impact: ">75%"

# Research Automation
research_automation:
  auto_capture:
    - brave_search_queries:
        capture_all: true
        categorize_by_topic: true
        track_effectiveness: true
    - context7_documentation:
        capture_accessed_libs: true
        track_usefulness: true
        document_findings: true
    - playwright_extractions:
        capture_sources: true
        track_completeness: true
        document_insights: true

  research_synthesis:
    auto_generate: true
    frequency: "on_research_completion"
    output_format: "research-template.md"
    include_metrics: true

# Testing Automation
testing_automation:
  auto_capture:
    - test_results:
        capture_all: true
        track_trends: true
        generate_reports: true
    - coverage_metrics:
        track_changes: true
        set_targets: true
        alert_on_decline: true
    - performance_benchmarks:
        capture_baseline: true
        track_regression: true
        alert_thresholds: true

  quality_gates:
    coverage_minimum: 80
    test_pass_rate: 95
    performance_regression: 5
    security_scan: required

# GitHub Integration
github_integration:
  workflows:
    - android_ci:
        triggers: ["push", "pull_request"]
        branches: ["main", "develop", "refactor/*"]
        jobs:
          - build
          - test
          - lint
          - security_scan
    - docs_update:
        triggers: ["push"]
        paths: ["docs/**"]
        jobs:
          - validate_docs
          - update_living_docs
          - deploy_docs

  automation:
    auto_merge:
      enabled: false  # Require manual review
      require_ci_pass: true
      require_reviews: 1
    auto_label:
      enabled: true
      rules:
        - pattern: "docs/**"
          label: "documentation"
        - pattern: "test/**"
          label: "testing"
        - pattern: "*.md"
          label: "documentation"

# Notification System
notifications:
  mcp_usage_alerts:
    context7_low_usage:
      threshold: 5
      message: "Context7 usage below target (15-20 weekly)"
      action: "Increase Android documentation research"
    brave_search_low_usage:
      threshold: 8
      message: "Brave Search usage below target (10-15 weekly)"
      action: "Increase technical research activities"
    github_mcp_issues:
      threshold: 90
      message: "GitHub MCP operations success rate below 90%"
      action: "Review and fix MCP integration issues"

  quality_alerts:
    test_coverage_decline:
      threshold: 5
      message: "Test coverage declined by more than 5%"
      action: "Review and improve test coverage"
    build_failures:
      threshold: 3
      message: "Multiple build failures detected"
      action: "Investigate and resolve build issues"

# Backup and Recovery
backup:
  frequency: "daily"
  retention: "30_days"
  include:
    - documentation_files
    - research_findings
    - test_artifacts
    - mcp_usage_logs

# Validation Rules
validation:
  documentation:
    required_sections:
      - goal
      - research_conducted
      - files_modified
      - testing_done
      - result
    mcp_integration:
      require_mcp_usage: true
      validate_effectiveness: true
      check_completeness: true

  research:
    quality_checks:
      - source_credibility
      - information_recency
      - technical_accuracy
      - practical_value
    mcp_validation:
      - brave_search_relevance: ">7.0"
      - context7_usefulness: ">7.0"
      - playwright_completeness: ">85%"

  testing:
    coverage_requirements:
      unit_tests: 80
      integration_tests: 70
      system_tests: 60
    quality_checks:
      - test_pass_rate: ">95%"
      - no_regression: true
      - performance_stable: true

# Reporting and Analytics
reporting:
  weekly_reports:
    generate: true
    recipients: ["development_team"]
    include:
      - mcp_usage_stats
      - research_effectiveness
      - testing_quality
      - documentation_completeness

  monthly_analytics:
    generate: true
    include:
      - trend_analysis
      - optimization_recommendations
      - quality_improvements
      - efficiency_gains

# Continuous Improvement
improvement:
  feedback_collection:
    enabled: true
    sources:
      - agent_session_reports
      - mcp_usage_reviews
      - quality_assessments
    analysis:
      auto_categorize: true
      generate_insights: true
      create_action_items: true

  optimization_cycles:
    frequency: "monthly"
    focus_areas:
      - mcp_server_usage
      - research_effectiveness
      - testing_efficiency
      - documentation_quality
    improvement_targets:
      - reduce_research_time: 20%
      - increase_test_coverage: 5%
      - improve_mcp_effectiveness: 15%
      - enhance_doc_findability: 30%